name: r_dotted_line_border
description: A Flutter decoration box package about dotted line border.
version: 0.1.1
homepage: https://github.com/rhymelph/r_dotted_line_border

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  coolint: 2.0.0

flutter:
